apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - name: 2181tcp01-zookeeper
      port: 2181
      protocol: TCP
      targetPort: 2181
    - name: 2888tcp01-zookeeper
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: 3888tcp01-zookeeper
      port: 3888
      protocol: TCP
      targetPort: 3888
  sessionAffinity: None
  type: ClusterIP
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: zookeeper
          imagePullPolicy: Always
          name: zookeeper
          ports:
            - containerPort: 2181
              hostPort: 2181
              name: 2181tcp21810
              protocol: TCP
            - containerPort: 2888
              name: 2888tcp01
              protocol: TCP
            - containerPort: 3888
              name: 3888tcp01
              protocol: TCP
            - containerPort: 8080
              name: 8080tcp01
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /datalog
              name: datalog
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
    - metadata:
        name: datalog
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
