apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cli
  namespace: kafka
spec: 
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-kafka-cli
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-kafka-cli
    spec:
      containers:
        - image: fernandokarnagi/kafka-cli:v1
          imagePullPolicy: Always
          name: kafka-cli
          args:
            - kafka-cli
            - kafka-console-producer.sh
            - --broker-list kafka-service:9092
            - --topic test
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler