apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
  namespace: kafka
spec:
  containers:
    - image: fernandokarnagi/kafka-cli:v2
      imagePullPolicy: Always
      name: kafka-cli
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler