apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-produce
  namespace: kafka
spec:  
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: fernandokarnagi/kafka-cli:v1
          imagePullPolicy: Always
          name: kafka-cli
          args:
            - kafka-console-producer.sh
            - --broker-list kafka-service:9092
            - --topic test