apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "2181": kafka/zookeeper-service:2181
  "19092": kafka/kafka-0-broker-service:19092
  "19093": kafka/kafka-1-broker-service:19093
  "19094": kafka/kafka-2-broker-service:19094